### ISSUE TITLE
License missing?

### ISSUE THREAD

**Issue by gavanderhoorn** [atolab/Zeno-He#1]
In [your post](https://discourse.ros.org/t/ipc-in-ros2/2619/18) to ROS Discourse you state that this code is under Apache 2:

> I wanted to let you know that we have just released under Apache 2 a peer-to-peer implementation of our zenoh protocol called Zeno-He (Zenoh Helium).

Right now however this repository does not contain any `LICENSE` file, nor do any of the files have license headers.

**Comment by kydos** [comment]
Good catch @gavanderhoorn ! The Apache 2 licensing file has now been committed. Thanks again for catching that.

Ciao!
